[package]
name = "mockql-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Command-line interface for GenAI-powered GraphQL response mocking via @mock"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "mockql"
path = "src/main.rs"

[dependencies]
axum.workspace = true
clap.workspace = true
humantime.workspace = true
mockql-core = { path = "../mockql-core", version = "=0.0.2" }
reqwest.workspace = true
serde_json.workspace = true
serde_json_bytes.workspace = true
thiserror.workspace = true
tokio.workspace = true
